-- MySQL Script generated by MySQL Workbench
-- Sat Sep 1 3:40:09 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cogip
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cogip
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cogip` DEFAULT CHARACTER SET utf8 ;
USE `cogip` ;

-- -----------------------------------------------------
-- Table `cogip`.`types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cogip`.`types` (
  `id_types` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_types`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cogip`.`societe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cogip`.`societe` (
  `id_societe` INT NOT NULL AUTO_INCREMENT,
  `nom_societe` VARCHAR(45) NOT NULL,
  `pays_societe` VARCHAR(45) NOT NULL,
  `tva_societe` INT NOT NULL,
  `telephone_societe` INT NOT NULL,
  `types_id_types` INT NOT NULL,
  PRIMARY KEY (`id_societe`),
  CONSTRAINT `fk_societe_types`
    FOREIGN KEY (`types_id_types`)
    REFERENCES `cogip`.`types` (`id_types`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cogip`.`personnes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cogip`.`personnes` (
  `id_personnes` INT NOT NULL AUTO_INCREMENT,
  `prenom_personne` VARCHAR(45) NOT NULL,
  `nom_personnes` VARCHAR(45) NOT NULL,
  `telephone_personnes` INT NOT NULL,
  `email_personnes` VARCHAR(45) NOT NULL,
  `societe_id_societe` INT NOT NULL,
  PRIMARY KEY (`id_personnes`),
  CONSTRAINT `fk_personnes_societe1`
    FOREIGN KEY (`societe_id_societe`)
    REFERENCES `cogip`.`societe` (`id_societe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cogip`.`factures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cogip`.`factures` (
  `id_factures` INT NOT NULL AUTO_INCREMENT,
  `numero_facture` INT NOT NULL,
  `date_facture` DATE NOT NULL,
  `objet_facture` VARCHAR(45) NOT NULL,
  `societe_id_societe` INT NOT NULL,
  `personnes_id_personnes` INT NOT NULL,
  PRIMARY KEY (`id_factures`),
  CONSTRAINT `fk_factures_societe1`
    FOREIGN KEY (`societe_id_societe`)
    REFERENCES `cogip`.`societe` (`id_societe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factures_personnes1`
    FOREIGN KEY (`personnes_id_personnes`)
    REFERENCES `cogip`.`personnes` (`id_personnes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
